### ISSUE TITLE
Facebook All Notifications whited out

### ISSUE THREAD

**Issue by daveo76** [dtinth/dark-facebook#28]
As you see on the screenshot that any txt that is on a white background
![fb](https://cloud.githubusercontent.com/assets/7221776/2640874/bbfcba76-beef-11e3-8f2b-2ae8844ab255.png)

**Comment by dtinth** [comment]
Thank you! It will be fixed shortly...

**Comment by daveo76** [comment]
That ok always willing to help out. Do you accept visa for donations

**Comment by dtinth** [comment]
Hello. Thanks for your interest in donation.

I used Pledgie to accept donations, which uses Paypal, which supports Visa, I think.
