### ISSUE TITLE
Settings Page: white background, text unreadable

### ISSUE THREAD

**Issue by daveo76** [dtinth/dark-facebook#29]
As you see on the screenshot. Anything I select on that all comes up white. Using your latest update (2014-04-08 (da28614) [common/standard-frame, notifications] Fix the notifications page.)
![fb](https://cloud.githubusercontent.com/assets/7221776/2641785/b30f7ca0-befe-11e3-84d0-45b08eaf7cda.png)

**Comment by daveo76** [comment]
same thing apply for everything settings on https://www.facebook.com/settings

**Comment by dtinth** [comment]
Wow, there's a lot to be fixed in the settings page..

This will be fixed soon; might not be today though. Thanks for the report.

**Comment by daveo76** [comment]
Also get the same problem on social fixer when I click it question mark symbol
![fb](https://cloud.githubusercontent.com/assets/7221776/2663335/76b0b0ae-c056-11e3-9027-317f7979d97f.png)

**Comment by dtinth** [comment]
That is another issue. I'll open one for you.

Please create a separate issue for each one, so that I can close them separately! Thanks!

**Comment by daveo76** [comment]
ok
