### ISSUE TITLE
[broken] Messages container loses styling

### ISSUE THREAD

**Issue by GuardianMajor** [dtinth/dark-facebook#31]
As you requested to have a new issue for each problem, I am posting this here on its own. I noticed that in the past few days, the messages when you go are all formatting properly but if you archive your message, the last message that you archive will remove the formatting for the container and turns it white. See below:

![messages_blank](https://cloud.githubusercontent.com/assets/5274181/2794817/a23bc082-cbf1-11e3-9e3c-6179e4024988.png)

**Comment by dtinth** [comment]
Does it only happen when all messages are removed? I don't want to archive all my conversations. :S

If so, then this is a rare case.

**Comment by GuardianMajor** [comment]
Yes, when all the messages are removed (by clicking on the little x that archives them) it will do that. It is very consistent behavior for me, happens all the time.

**Comment by GuardianMajor** [comment]
I just did it for you again, easy to do every time, as you ca see in the picture, have a message, click on archive, no more messages and the left is white and the the text in the right container is gone too. Persistent and consistent.

![messages](https://cloud.githubusercontent.com/assets/5274181/2813252/05d362d4-ce82-11e3-843f-1612f78b7112.png)

**Comment by GuardianMajor** [comment]
Another piece of information that might be relevant to helping you debug this is that if you go directly to (https://www.facebook.com/messages?action=recent-messages) when you don't have any messages in your inbox, you also get the white container. The ONLY time it will not be white is when there is an actual message present in the inbox.

**Comment by dtinth** [comment]
It should look quite polished now. 

![screen shot 2014-05-22 at 2 24 52 pm](https://cloud.githubusercontent.com/assets/193136/3050884/3b9cde0a-e182-11e3-95d9-fa011bd02198.png)

**Comment by GuardianMajor** [comment]
@dtinth 
Confirmed, good work.

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/5274181/3061955/879a9870-e212-11e3-8f69-eabeb92654a6.png)

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/5274181/3061957/8bf43d7c-e212-11e3-97c7-c1d5230c9c78.png)
