### ISSUE TITLE
[broken] Drop Menu has lost styling

### ISSUE THREAD

**Issue by GuardianMajor** [dtinth/dark-facebook#33]
As agreed I posted this issue separately here a couple days ago but I came today to report something else and it was gone, not closed, just gone, so I figured I post again.

The drop down menu has suddenly lost styling again, it was styled properly and working before but as of a couple days ago it has lost it again.

![drop_menu](https://cloud.githubusercontent.com/assets/5274181/2794936/515d0c78-cbf3-11e3-8edc-72e558f568c6.png)

**Comment by dtinth** [comment]
Thanks for your report.

I'm quite busy with studies and other stuff right now, so that's why there are no updates in the past week. I'll update them when things clear up a bit.

**Comment by GuardianMajor** [comment]
@dtinth 
You are welcome and no worries take care of your things, I am just reporting for sake of keeping track of issues to be done, that's all.

**Comment by GuardianMajor** [comment]
@dtinth 
Confirmed, good work.

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/5274181/3061932/0e1f2a06-e212-11e3-99c1-099215a702d4.png)

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/5274181/3061933/15b66234-e212-11e3-8be6-4e0d4c258379.png)
