### ISSUE TITLE
Styling in chat broken

### ISSUE THREAD

**Issue by WtheFourth** [dtinth/dark-facebook#34]
White box between user picture and chat box, see attached.

---

![fb dark messages broke](https://cloud.githubusercontent.com/assets/788900/3023155/a4511a74-dfde-11e3-80de-bbe460d2dba0.png)

**Comment by dtinth** [comment]
Seems like Facebook has just changed the CSS classes again.

When I have more free time I'll investigate the issues (and others).

Thanks for reporting!
