### ISSUE TITLE
[broken] Request Page

### ISSUE THREAD

**Issue by GuardianMajor** [dtinth/dark-facebook#35]
![requests_-_app_center_-_2014-05-22_17 56 39](https://cloud.githubusercontent.com/assets/5274181/3062184/7e595a20-e218-11e3-9f24-4c0180d62c53.png)

**Comment by dtinth** [comment]
The app center (Home and Requests page) has been polished. :D

**Comment by GuardianMajor** [comment]
Much better, the header, the suggested games background is definitely polished but not quite 100% yet, see below:

Firefox
![firefox](https://cloud.githubusercontent.com/assets/5274181/3076241/824709a0-e3c3-11e3-8035-44d4d361bfa3.png)

Chrome
![chrome](https://cloud.githubusercontent.com/assets/5274181/3076242/8bc293a0-e3c3-11e3-8d9b-997153d6c8b4.png)

**Comment by GuardianMajor** [comment]
Additionally, upon cancelling an app, such as the one above in my screenshot, you get this nearly impossible to read result that looks fine on white background that is default but in dark, not so much:

![cancel](https://cloud.githubusercontent.com/assets/5274181/3076246/efdd5532-e3c3-11e3-9e2e-06efe9b8e9bf.png)

clicking to block the app shows up just fine though, styled properly throughout.
