### ISSUE TITLE
[side effect] social plugin containers are wrong

### ISSUE THREAD

**Issue by GuardianMajor** [dtinth/dark-facebook#36]
![_-_2014-05-27_14 20 13](https://cloud.githubusercontent.com/assets/5274181/3098023/72188f70-e5e6-11e3-99dd-08e19ab113db.png)

The formatting as you can see far exceeds the width of the plugin and so it looks very wrong, I can send you a full screen shot to highlight this issue if it makes it easier but I think the image is pretty clear on this issue.

**Comment by dtinth** [comment]
This is quite complicated, as it integrates with other pages. It's fixed
for next update.

After the update is deployed, if you see problems with other plugins, this
may have to be reverted.

**Comment by GuardianMajor** [comment]
@dtinth 
Ok, will look forward to testing and posting confirmation.

**Comment by GuardianMajor** [comment]
Confirmed, great work.

Firefox
![firefox](https://cloud.githubusercontent.com/assets/5274181/3112330/34b13cac-e6bf-11e3-88b8-91d75a317c02.png)

Chrome
![chrome](https://cloud.githubusercontent.com/assets/5274181/3112331/38d13850-e6bf-11e3-9af0-3c4f21dd0ae4.png)
