### ISSUE TITLE
[inconsistent] the event page formatting is wrong

### ISSUE THREAD

**Issue by GuardianMajor** [dtinth/dark-facebook#37]
When you load the event page all is fine but when you comment, say wishing someone a happy birthday or something, the coloring becomes impossible to see due to the contrast, see below:

![13 _events_-_2014-05-25_12 28 11](https://cloud.githubusercontent.com/assets/5274181/3098044/c5a1b4e6-e5e6-11e3-93e9-9f97f3c4e7d9.png)

**Comment by dtinth** [comment]
Fixed for next update.

**Comment by GuardianMajor** [comment]
@dtinth 
Wonderful, look forward to testing and posting confirmation.

**Comment by GuardianMajor** [comment]
@dtinth 
Confirmed, working. It briefly remains yellow like the image above but then quickly goes blue.

![1 _events_-_2014-05-29_13 09 24](https://cloud.githubusercontent.com/assets/5274181/3122943/7bfc46ca-e76d-11e3-9776-a7744f769afc.png)
