### ISSUE TITLE
Bubble Chat

### ISSUE THREAD

**Issue by MegaMoses** [dtinth/dark-facebook#4]
The chat text needs to be styled darker so that it is visible against the bright colors of the chat bubbles.  Otherwise the chat bubbles need to be darkened or removed.

**Comment by dtinth** [comment]
Thank you for your report. However, work is being done on the next
generation of this theme.

The current generation of this theme is so unmaintainable now... The next
generation will be more resistant to facebook's theme changes, easier to
modify, fix, maintain, and contribute to.

Please stay tuned to the next version. :D

You can see the work as they are being worked on on branch dfb2 of this
repository.

**Comment by Bijan-A** [comment]
Is there an ETA for the next version? :)

**Comment by dtinth** [comment]
About 1 to 2 weeks, hopefully.

Within this week I will try to get the development version up on
Userstyles.org (but it's an incomplete theme) and set up automatic
deployment, so you can try it out.

Then I'll try to get a lot of parts done in the subsequent week.

**Comment by dtinth** [comment]
Fixed in dfb2 branch...

You can test it in this user style: http://userstyles.org/styles/95359/facebook-dark-facebook-2-work-in-progress
