### ISSUE TITLE
Too many things not working

### ISSUE THREAD

**Issue by TriMoon** [dtinth/dark-facebook#41]
Just letting you guys that too many things ain't working when you use this theme.
New users of this theme, me included, will switch-off of this theme after 5mins use !

Please test at least the most used and visual functionalities very soon, or just remove this theme.
Too bad cause i like the dark theme it provides, but use of SocialFixer is more important.
Have a nice day.

**Comment by dtinth** [comment]
I'm quite busy at the moment and don't have time to fix many things yet. Yes, they will be fixed soon.

Closing this issue since it did not address any specific problem.
