### ISSUE TITLE
bug in clicking the icon smiley  in chat message

### ISSUE THREAD

**Issue by xsoultribex** [dtinth/dark-facebook#44]
![screenshot from 2014-07-15 23 43 36](https://cloud.githubusercontent.com/assets/8170895/3587077/e524c978-0c35-11e4-9109-40a577289a3e.png)

theres a bug in clicking the smiley icon in chat,there was grid line, hope this will soon.. i really this theme style... & also this one it looks ugly..
![screenshot from 2014-07-15 23 56 24](https://cloud.githubusercontent.com/assets/8170895/3587291/a4348d5c-0c37-11e4-8189-8ff8a099cd14.png)

**Comment by dtinth** [comment]
Hello. Thank you for reporting. Facebook changed its stylesheet again for the menu.

I am very busy with doing my internship, so expect that it will take some time for this to get fixed.

**Comment by xsoultribex** [comment]
ok mate thanks  :) .. i'll wait your update.. this theme of yours is my favorite style sheet...
