### ISSUE TITLE
Top bar is blue

### ISSUE THREAD

**Issue by Bijan-A** [dtinth/dark-facebook#45]
![image](https://cloud.githubusercontent.com/assets/116760/3667654/642718b0-1209-11e4-8474-af781afde68f.png)

The top bar does not match and is blue.

**Comment by WtheFourth** [comment]
Additionally, all the FR/Messages/Notifications popouts have lost their inlay coloring.

# 

![image](https://cloud.githubusercontent.com/assets/788900/3668049/9b16420c-1212-11e4-9e1f-aad85799bff8.png)

**Comment by dtinth** [comment]
Thanks for reporting!

This is already fixed in 3cc3a0a and c8dfda7, respectively. Please update your style. :dancers:
