### ISSUE TITLE
Black Theme ceased working unexpectedly | SocialFixer v10.4

### ISSUE THREAD

**Issue by Silent-Street** [dtinth/dark-facebook#47]
Black theme chosen, but ceases to work. FB defaults to standard. :-(
Disappointing as the black theme is very attractive and easy going as an interface. :-)

**Comment by dtinth** [comment]
For Social Fixer users, please check out the [dark-facebook Social Fixer Troubleshooting Page](https://github.com/dtinth/dark-facebook/wiki/Troubleshooting:-Theme-Stops-Working-Completely-on-Social-Fixer).
