### ISSUE TITLE
Not working with Social Fixer

### ISSUE THREAD

**Issue by methos237** [dtinth/dark-facebook#48]
Selecting the theme through the Social Fixer extension on Firefox does not work, only shows standard FB css styling

**Comment by dtinth** [comment]
For Social Fixer users, please check out the [dark-facebook Social Fixer Troubleshooting Page](https://github.com/dtinth/dark-facebook/wiki/Troubleshooting:-Theme-Stops-Working-Completely-on-Social-Fixer).
