### ISSUE TITLE
Text on Notifications Feed Not Visible

### ISSUE THREAD

**Issue by HsvIllini** [dtinth/dark-facebook#49]
With Social Fixer version 10.6, the text in the notifications feed area is no longer visible unless you move the mouse over an entry to highlight it.

![image](https://cloud.githubusercontent.com/assets/8319224/3762892/2bd1d402-189c-11e4-83c9-12e520adc4d8.png)

**Comment by dtinth** [comment]
The ticker color has been fixed. 01c713a

**Comment by HsvIllini** [comment]
Thanks so much! My favorite theme is usable once again :)
