### ISSUE TITLE
light Grey background under left part

### ISSUE THREAD

**Issue by elKixo** [dtinth/dark-facebook#51]
we can see a light Grey background under the left part of the page (under friends, groups, applications...) ans the text is black
![facebook - mozilla firefox](https://cloud.githubusercontent.com/assets/8568700/4060208/be53854e-2ded-11e4-80e2-8b75768002bb.jpg)

**Comment by dtinth** [comment]
Acknowledged. Right now I am busy with other stuff. I will fix it afterwards.

Please understand that this will take some time.  Thank you! :D

—

**Comment by elKixo** [comment]
no problem!
thank you for this nice theme ;)

2014-08-28 5:16 GMT+02:00 Thai Pangsakulyanont notifications@github.com:

> Acknowledged. Right now I am busy with other stuff. I will fix it
> afterwards.
> 
> Please understand that this will take some time. Thank you! :D
> 
> —
> Sent from Mailbox
>

**Comment by dtinth** [comment]
Fixed by 64385c608514e56930b08136998e7499397a8038.

Please update your theme.

**Comment by elKixo** [comment]
thanks!

2014-09-04 4:52 GMT+02:00 Thai Pangsakulyanont notifications@github.com:
