### ISSUE TITLE
Dark facebook not working

### ISSUE THREAD

**Issue by alanturnell** [dtinth/dark-facebook#59]

**Comment by alanturnell** [comment]
Dark facebook has stopped working

**Comment by princealbertofpa** [comment]
ditto....

**Comment by ghost** [comment]
Same. Specifically (for me, at least), under Chrome through Social Fixer. The news sidebar appears to still be modified partially, as the text is light-gray, as opposed to black (if the whole theme was non-functional).

Probably a Facebook-level change, I'm guessing.
![dark_fb_notworking](https://cloud.githubusercontent.com/assets/1232245/5599436/110b3952-927b-11e4-9892-d45e7721f2c8.PNG)

**Comment by princealbertofpa** [comment]
they are aware of the problem...
![screen shot 2015-01-02 at 3 38 12 pm](https://cloud.githubusercontent.com/assets/2357617/5599492/93f81a8c-9295-11e4-9da8-67001460e35e.jpeg)

**Comment by alanturnell** [comment]
Many thanks.
Alan Turnell.

Date: Wed, 28 Jan 2015 21:02:34 -0800
