### ISSUE TITLE
Dark Facebook theme is gone

### ISSUE THREAD

**Issue by ghost** [dtinth/dark-facebook#61]
Just happened about 5 minutes ago. Others using SFx have posted the issue in their forum. Help, please?

**Comment by dtinth** [comment]
Please see this page first: https://github.com/dtinth/dark-facebook/wiki/Troubleshooting:-Theme-Stops-Working-Completely-on-Social-Fixer

**Comment by ghost** [comment]
Thank you very much. I bookmarked the troubleshooting page you sent.
