### ISSUE TITLE
Theme is not working but

### ISSUE THREAD

**Issue by amitku7** [dtinth/dark-facebook#69]
Theme isn't working but the monochrome app one is working 
tps://hoof.little.my/files/mono.css?x=48.56231689453125&y=2.4 thats the link to it

**Comment by dtinth** [comment]
Have you tried the alternative URL and/or alternative methods described here?

https://github.com/dtinth/dark-facebook/wiki/Troubleshooting:-Theme-Stops-Working-Completely-on-Social-Fixer

**Comment by amitku7** [comment]
Oh cheers man
